version: '3.8'
services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - spring-boot-network
    environment:
      MYSQL_ROOT_PASSWORD: "Trung381@#$%"
    volumes:
      - ./mysql-data:/var/lib/mysql
  app:
    image: trung381/logistic_management:lst
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logistic-app
    ports:
      - 8080:8080
    networks:
      - spring-boot-network
    environment:
      SECRET_KEY: 404E635266556A586e3272357538782F413F4428472B4B6250645367566b5970
      DB_URL: jdbc:mysql://mysql:3306/logistic_management?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: "Trung381@#$%"
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
networks:
  spring-boot-network:
